export const invitedUsers = [
  {
    id: '1',
    username: 'jesica_joseph',
    fullname: 'Jesica Joseph',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '2',
    username: "jenny_d'souza",
    fullname: "Jenny D'souza",
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '3',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '4',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '5',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '6',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '7',
    username: 'jesica_joseph',
    fullname: 'Jesica Joseph',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '8',
    username: "jenny_d'souza",
    fullname: "Jenny D'souza",
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '9',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '10',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '11',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '12',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '13',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
  {
    id: '14',
    username: 'WilsonDukes',
    fullname: 'Wilson Dukes',
    image: require('../../assets/images/ProfileImage.png'),
  },
];
