export { default as Switch } from './General/Switch/Switch';
export { default as SettingsItem } from './Settings/SettingsItem/SettingsItem';
export { default as SettingsSection } from './Settings/SettingsSection/SettingsSection';
export { default as ProfilePhotoSelector } from './ProfilePhotoSelector/ProfilePhotoSelector';
export { default as DisplayName } from './DisplayName/DisplayName';
export { default as AccountSettingsItem } from './MyAccount/AccountSettingsItem/AccountSettingsItem';
export { default as MoreOptionsItem } from './MyAccount/MoreOptionsItem/MoreOptionsItem';
export { default as QRCodeCard } from './QrCode/QRCodeCard/QRCodeCard';
export { default as ActionButtons } from './QrCode/ActionButtons/ActionButtons';
export { default as BlockedUserItem } from './BlockedContacts/BlockedUserItem/BlockedUserItem';
// export * from './Icons/SettingsIcons';
// export * from './AccountIcons/AccountIcons';
