
import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');
const HALF = (width - 5) / 2;

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#eaeaea', },
  phoneCard: {
    flex: 1,
    // margin: 12,
    overflow: 'hidden',
    paddingTop: 25,
    backgroundColor: '#111',
  },
  splitWrap: { flex: 1 },
  side: { position: 'absolute', top: 0, bottom: 0, width: HALF },
  leftSide: { left: 0 },
  rightSide: { right: 0 },
  divider: {
    position: 'absolute',
    left: '50%',
    top: 10,
    bottom: 10,
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  coinsPill: {
    position: 'absolute',
    top: 14,
    backgroundColor: '#f5c84b',
    paddingHorizontal: 12,
    height: 28,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coinsText: { color: '#2d1f05', fontWeight: '900' },
  nameWrap: {
    position: 'absolute',
    top: 52,
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameText: { color: '#fff', fontWeight: '800', marginLeft: 8 },
  avatarRing: {
    width: 30,
    height: 30,
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#8b5cf6',
  },
  avatar: { width: '100%', height: '100%' },
  vsWrap: {
    position: 'absolute',
    top: 10,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  vsText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 38,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  timerPill: {
    marginTop: 6,
    backgroundColor: 'rgba(98,76,255,0.95)',
    paddingHorizontal: 10,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerText: { color: '#fff', fontWeight: '800' },
  bottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 180,
  },
  chatLayer: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 100,
  },
  chatRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  chatAvatar: { width: 30, height: 30, borderRadius: 15, marginRight: 8 },
  chatBubble: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chatName: { color: '#fff', fontWeight: '800', marginRight: 6 },
  verifiedDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#3b82f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  chatText: { color: '#fff', opacity: 0.95, marginTop: 2 },
  countPill: {
    marginLeft: 4,
    paddingHorizontal: 8,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#f59e0b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countText: { color: '#111', fontWeight: '900' },
  bottomBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputWrap: {
    flex: 1,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginRight: 8,
  },
  input: { color: '#fff' },
  circleBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  heartBtn: { backgroundColor: '#ef4444' },

  backdrop: { flex: 1, backgroundColor: '#000' },
  bottomSafe: { flex: 1, justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    // maxHeight: '78%',
    height:"50%",
    paddingBottom: 8,
  },
  sheetHeader: {
    height: 52,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#ececec',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetTitle: { fontSize: 16, fontWeight: '800', color: '#333' },
  closeBtn: { position: 'absolute', right: 12, top: 10, width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  closeText: { fontSize: 18, color: '#9aa0a6' },
  coinsWrap: { alignItems: 'center', paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#f0f0f0' },
  coinsValue: { fontSize: 30, fontWeight: '900', color: '#a855f7' },
  coinsLabel: { color: '#8a8a96', marginTop: 2 },
  grid: { flexDirection: 'row',flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 5, columnGap: 5 },
  itemCard: { width: '24%',aspectRatio:1, backgroundColor:"#F9F9F9", borderRadius: 3, paddingVertical: 10, alignItems: 'center',  },
  itemEmoji: { fontSize: 30 },
  itemCoins: { marginTop: 6, color: '#7a7a86' },
  sendBtn: { marginTop: 6 },
  sendText: { color: '#a855f7', fontWeight: '900', letterSpacing: 0.5 },

  // Demo button
  demoOpenBtn: { backgroundColor: '#a855f7', paddingHorizontal: 18, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
});
export default styles;